version: "3.8"
services:
  camunda7:
    image: camunda/camunda-bpm-platform:latest
    container_name: camunda7
    ports:
      - "8080:8080"
    environment:
      - TZ=Asia/Kolkata

  mongo:
    image: mongo:6
    container_name: mongo_local
    restart: unless-stopped
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db

volumes:
  mongo_data:
